<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>BiBiVoiceWin</AssemblyName>
    <RootNamespace>BiBiVoiceWin</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="NAudio.Wasapi" Version="2.2.1" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="UIAutomationClient">
      <HintPath>$(MSBuildProgramFiles32)\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\8.0.8\ref\net8.0\UIAutomationClient.dll</HintPath>
    </Reference>
    <Reference Include="UIAutomationTypes">
      <HintPath>$(MSBuildProgramFiles32)\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\8.0.8\ref\net8.0\UIAutomationTypes.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BiBiVoiceWin.Shared\BiBiVoiceWin.Shared.csproj" />
  </ItemGroup>
</Project>
